// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK7MQ1lz8uDnM0U9thiUxBGdt-K-mKA8o',
    appId: '1:516679825981:android:a527e41645a6d444c60854',
    messagingSenderId: '516679825981',
    projectId: 'softech2025-7b3cd',
    storageBucket: 'softech2025-7b3cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ37EBRf6u-k81m4QDg8zZf5p3pctsjgM',
    appId: '1:516679825981:ios:4a5c98acc6afa024c60854',
    messagingSenderId: '516679825981',
    projectId: 'softech2025-7b3cd',
    storageBucket: 'softech2025-7b3cd.firebasestorage.app',
    iosBundleId: 'com.example.soft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ37EBRf6u-k81m4QDg8zZf5p3pctsjgM',
    appId: '1:516679825981:ios:4a5c98acc6afa024c60854',
    messagingSenderId: '516679825981',
    projectId: 'softech2025-7b3cd',
    storageBucket: 'softech2025-7b3cd.firebasestorage.app',
    iosBundleId: 'com.example.soft',
  );
}
